//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 07:42:56 PM EEST 
//


package com.example.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccountState"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Active"/&gt;
 *     &lt;enumeration value="Frozen"/&gt;
 *     &lt;enumeration value="Locked"/&gt;
 *     &lt;enumeration value="Inactive"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AccountState")
@XmlEnum
public enum AccountState {

    @XmlEnumValue("Active")
    ACTIVE("Active"),
    @XmlEnumValue("Frozen")
    FROZEN("Frozen"),
    @XmlEnumValue("Locked")
    LOCKED("Locked"),
    @XmlEnumValue("Inactive")
    INACTIVE("Inactive");
    private final String value;

    AccountState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccountState fromValue(String v) {
        for (AccountState c: AccountState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
