//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 07:42:56 PM EEST 
//


package com.example.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpensesCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExpensesCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Cat1"/&gt;
 *     &lt;enumeration value="Cat2"/&gt;
 *     &lt;enumeration value="Cat3"/&gt;
 *     &lt;enumeration value="Cat4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ExpensesCategory")
@XmlEnum
public enum ExpensesCategory {

    @XmlEnumValue("Cat1")
    CAT_1("Cat1"),
    @XmlEnumValue("Cat2")
    CAT_2("Cat2"),
    @XmlEnumValue("Cat3")
    CAT_3("Cat3"),
    @XmlEnumValue("Cat4")
    CAT_4("Cat4");
    private final String value;

    ExpensesCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpensesCategory fromValue(String v) {
        for (ExpensesCategory c: ExpensesCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
