//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 07:42:56 PM EEST 
//


package com.example.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Outgoings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Outgoings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://example.com/spandandtrack}Payment"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" type="{http://example.com/spandandtrack}ExpensesCategory"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Outgoings", propOrder = {
    "category"
})
public class Outgoings
    extends Payment
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ExpensesCategory category;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link ExpensesCategory }
     *     
     */
    public ExpensesCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpensesCategory }
     *     
     */
    public void setCategory(ExpensesCategory value) {
        this.category = value;
    }

}
