//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 07:42:56 PM EEST 
//


package com.example.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserState"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Unregistred"/&gt;
 *     &lt;enumeration value="Unconfirmed"/&gt;
 *     &lt;enumeration value="Confirmed"/&gt;
 *     &lt;enumeration value="Logged in"/&gt;
 *     &lt;enumeration value="Logged out"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UserState")
@XmlEnum
public enum UserState {

    @XmlEnumValue("Unregistred")
    UNREGISTRED("Unregistred"),
    @XmlEnumValue("Unconfirmed")
    UNCONFIRMED("Unconfirmed"),
    @XmlEnumValue("Confirmed")
    CONFIRMED("Confirmed"),
    @XmlEnumValue("Logged in")
    LOGGED_IN("Logged in"),
    @XmlEnumValue("Logged out")
    LOGGED_OUT("Logged out");
    private final String value;

    UserState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UserState fromValue(String v) {
        for (UserState c: UserState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
