package com.edvantis.workopolis.MongoDB;

public enum Direction {
	ADMINISTRATION,
	BUSINESS_ANALYSIS,
	DESIGN,
	DATABASES,
	PROJECT_MANAGEMENT,
	QUALITY_CONTROL,
	SOFTWARE_DEVELOPMENT,
	SYSTEM_ARCHITECTURE,
}
