package com.edvantis.workopolis.model.skill;

public enum PersonalSkillName {
	OPENESS_TO_EXPERIENCE, 
	CONSCIENTIOUSNESS, 
	EXTRAVERSION, 
	AGREEABLENESS, 
	TEUROTICISM,
	TEAMWORK,
	INITIATIVE,
	FLEXIBILITY,
	TIME_MANAGEMENT,
	DECISION_MAKING,
	CREATIVITY,
	TRUSTWORTHINESS,
	EMOTIONAL_STABILITY

}
