package com.edvantis.workopolis.model.education;

public enum EducationField {
	AUTOMATION_AND_MACHINE_CONSTRUCTING,
	ELECTRONICS_AND_TELECOMMUNICATIONS,
	SYSTEM_ANALYSIS,
	COMPUTER_SCIENCE,
	SOFTWARE_ENGINEERING,
	SYSTEM_ARCHITECTURE,
	PROJECT_MANAGEMENT,
	SYSTEM_PROGRAMMING,
	METROLOGY_AND_MEASURING_EQUIPMENT,
	INFORMATION_TECHNOLOGY,
	INFORMATION_AND_COMMUNICATION,
	SYSTEMS_SECURITY,
	INFORMATION_SECURITY_MANAGEMENT,
	QUALITY_STANDARTIZATION_AND_CERTIFICATION,
	APPLIED_MATHEMATICS,
	APPLIED_PHYSICS,
	MATHEMATICAL_AND_COMPUTER_MODELING
}
